// src/styles/formStyles.js

export const styles = {
    wrapper: {
        fontFamily: "Arial, sans-serif",
        fontSize: "13px",
        backgroundColor: "#fbfcff",
        minHeight: "90vh",
        display: "flex",
        justifyContent: "center",
        width: "100%",
    },
    panel: {
        backgroundColor: "#fff",
        border: "1px solid #d1d5db",
        borderRadius: "8px",
        width: "96%",
        overflow: "hidden",
        boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    },
    panelHeader: {
        backgroundColor: "#374151",
        color: "#fff",
        padding: "4px 20px",
        fontSize: "16px",
        fontWeight: "600",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
    },
    helpBtn: {
        width: "24px",
        height: "24px",
        borderRadius: "50%",
        border: "1.5px solid #fff",
        background: "transparent",
        color: "#fff",
        fontSize: "13px",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontWeight: "bold",
        padding: 0,
    },
    sectionHeader: {
        backgroundColor: "#4b5563",
        color: "#fff",
        fontSize: "12px",
        fontWeight: "600",
        padding: "8px 16px",
        margin: "16px -24px 16px",
        letterSpacing: "0.8px",
    },
    panelBody: {
        padding: "20px 28px 18px",
    },
    formRow: {
        display: "grid",
        gridTemplateColumns: "180px 12px 1fr",
        alignItems: "center",
        marginBottom: "14px",
        minHeight: "30px",
    },
    label: {
        textAlign: "right",
        fontSize: "13px",
        color: "#374151",
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        fontWeight: "500",
    },
    req: {
        color: "#dc2626",
        marginLeft: "3px",
        fontSize: "14px",
    },
    colon: {
        textAlign: "center",
        color: "#6b7280",
        fontSize: "13px",
        paddingLeft: "2px",
    },
    ctrl: {
        paddingLeft: "12px",
        display: "flex",
        alignItems: "center",
        gap: "8px",
    },
    inputSm: {
        height: "30px",
        width: "110px",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        outline: "none",
        backgroundColor: "#fff",
    },
    inputMd: {
        height: "30px",
        width: "240px",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        outline: "none",
        backgroundColor: "#fff",
    },
    inputLg: {
        height: "30px",
        width: "100%",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        outline: "none",
        backgroundColor: "#fff",
    },
    inputDate: {
        height: "30px",
        width: "200px",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        outline: "none",
        backgroundColor: "#fff",
    },
    select: {
        height: "30px",
        width: "220px",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        backgroundColor: "#fff",
        outline: "none",
        cursor: "pointer",
    },
    selectLg: {
        height: "30px",
        width: "100%",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        padding: "0 8px",
        backgroundColor: "#fff",
        outline: "none",
        cursor: "pointer",
    },
    divider: {
        borderTop: "1px solid #e5e7eb",
        margin: "20px 0",
    },
    btnRow: {
        display: "flex",
        justifyContent: "center",
        gap: "10px",
        paddingTop: "8px",
    },
    btn: {
        height: "32px",
        padding: "0 20px",
        fontSize: "13px",
        border: "1px solid #d1d5db",
        borderRadius: "4px",
        cursor: "pointer",
        background: "linear-gradient(to bottom, #f9fafb, #e5e7eb)",
        color: "#374151",
        fontWeight: "500",
    },
    toast: {
        position: "fixed",
        top: "24px",
        right: "24px",
        background: "#2e7d32",
        color: "#fff",
        padding: "12px 24px",
        borderRadius: "6px",
        fontSize: "14px",
        zIndex: 9999,
        boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    },
    checkboxContainer: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "4px 0",
    },

    checkbox: {
        width: "18px",
        height: "18px",
        cursor: "pointer",
        accentColor: "#4CAF50",
    },

    checkboxLabel: {
        fontSize: "13px",
        color: "#666",
        fontWeight: 500,
    },

    checkboxText: {
        fontSize: "13px",
        fontWeight: 600,
    },
    helpBtn: {
        padding: "6px 12px",
        fontSize: "16px",
        backgroundColor: "#fff",
        color: "#4a90d9",
        border: "none",
        borderRadius: "4px",
        cursor: "pointer",
        fontWeight: 600,
        transition: "all 0.2s",
        "&:hover": {
            backgroundColor: "#f0f0f0",
        },
    },
};